# Generated by Django 4.0.1 on 2022-01-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('imie', models.TextField(max_length=60)),
                ('nazwisko', models.TextField(max_length=60)),
                ('licencja', models.TextField(blank=True, max_length=60, null=True, verbose_name='Numer licencji')),
                ('licencja_sedziego', models.TextField(blank=True, max_length=60, null=True, verbose_name='Numer licencji sędziego')),
                ('klub', models.TextField(blank=True, max_length=60, null=True)),
                ('klasa_sedziego', models.TextField(blank=True, max_length=60, null=True, verbose_name='Klasa sędziego')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_sedzia', models.BooleanField(default=False)),
                ('is_rts', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
