# Generated by Django 4.0.1 on 2022-01-17 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
