# Generated by Django 4.0.1 on 2022-01-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0002_uzytkownik_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uzytkownik',
            options={'verbose_name_plural': 'Użytkownicy'},
        ),
        migrations.AlterField(
            model_name='uzytkownik',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
