# Generated by Django 3.2.9 on 2022-02-06 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0004_alter_uzytkownik_is_rts'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzytkownik',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
