# Generated by Django 3.2.9 on 2022-02-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0005_uzytkownik_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='slug',
            new_name='slug_user',
        ),
    ]
