# Generated by Django 3.2.9 on 2022-02-06 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uzytkownicy', '0006_rename_slug_uzytkownik_slug_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='slug_user',
            new_name='slug',
        ),
    ]
