# Generated by Django 4.0.1 on 2022-01-17 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zawody', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wyniki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.IntegerField(blank=True, default=0)),
                ('Xx', models.IntegerField(blank=True, default=0, verbose_name='10')),
                ('dziewiec', models.IntegerField(blank=True, default=0, verbose_name='9')),
                ('osiem', models.IntegerField(blank=True, default=0, verbose_name='8')),
                ('siedem', models.IntegerField(blank=True, default=0, verbose_name='7')),
                ('szesc', models.IntegerField(blank=True, default=0, verbose_name='6')),
                ('piec', models.IntegerField(blank=True, default=0, verbose_name='5')),
                ('cztery', models.IntegerField(blank=True, default=0, verbose_name='4')),
                ('trzy', models.IntegerField(blank=True, default=0, verbose_name='3')),
                ('dwa', models.IntegerField(blank=True, default=0, verbose_name='2')),
                ('jeden', models.IntegerField(blank=True, default=0, verbose_name='1')),
                ('wynik', models.IntegerField(blank=True, default=0)),
                ('rezultat', models.TextField(default='0', max_length=60, null=True)),
                ('kara', models.CharField(choices=[('BRAK', 'BRAK'), ('DNF', 'DNF'), ('DNS', 'DNS'), ('DSQ', 'DSQ'), ('PK', 'PK')], default='BRAK', max_length=10)),
                ('oplata', models.BooleanField(default=False)),
                ('konkurencja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.konkurencja', verbose_name='konkurencja')),
                ('zawodnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wyniki',
            },
        ),
    ]
