# Generated by Django 3.2.9 on 2022-02-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wyniki', '0002_wyniki_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='wyniki',
            name='kara_punktowa',
            field=models.IntegerField(blank=True, default=0, verbose_name='Kara punktowa'),
        ),
    ]
