# Generated by Django 4.0.1 on 2022-01-17 15:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Konkurencja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('liczba_strzalow', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name_plural': 'Konkurencja',
            },
        ),
        migrations.CreateModel(
            name='Turniej',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('rejestracja', models.BooleanField(verbose_name='Rejestracja')),
            ],
        ),
        migrations.CreateModel(
            name='Sedzia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konkurencja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zawody.konkurencja')),
                ('osoba', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sędziowie',
            },
        ),
        migrations.AddField(
            model_name='konkurencja',
            name='turniej',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='zawody.turniej'),
        ),
    ]
