# Generated by Django 3.2.9 on 2022-02-06 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='turniej',
            options={'verbose_name_plural': 'Turnieje'},
        ),
        migrations.AddField(
            model_name='konkurencja',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='turniej',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
