# Generated by Django 3.2.9 on 2022-02-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0003_auto_20220206_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='sedzia',
            name='slug',
            field=models.SlugField(default='1'),
            preserve_default=False,
        ),
    ]
