# Generated by Django 3.2.9 on 2022-02-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0004_sedzia_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='konkurencja',
            unique_together={('nazwa', 'turniej')},
        ),
    ]
