# Generated by Django 3.2.9 on 2022-02-06 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zawody', '0005_alter_konkurencja_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='turniej',
            name='klasyfikacja_generalna',
            field=models.BooleanField(default=True, verbose_name='Klasyfikacja generalna'),
        ),
    ]
